// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Share.Web.Data;

#nullable disable

namespace Share.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008105425_ArrivalsFeed")]
    partial class ArrivalsFeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Share.Web.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Council")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchKey")
                        .IsUnique();

                    b.ToTable("Accommodations");
                });

            modelBuilder.Entity("Share.Web.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsHidden", "PublishAt")
                        .IsDescending(false, true);

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Share.Web.Models.ApplicationAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("ApplicationAnswer");
                });

            modelBuilder.Entity("Share.Web.Models.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrivalRecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ArrivalRecordedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Council")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("MatchKey")
                        .IsUnique();

                    b.HasIndex("SponsorId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("Share.Web.Models.CaseCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DbsType")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaseId", "Kind")
                        .IsUnique();

                    b.ToTable("CaseCheck");
                });

            modelBuilder.Entity("Share.Web.Models.DecisionUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalPort")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decision")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gwf")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uan")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisaApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VoyageCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VisaApplicationId");

                    b.HasIndex("IngestRunId", "RowNumber")
                        .IsUnique();

                    b.ToTable("DecisionUpdates");
                });

            modelBuilder.Entity("Share.Web.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gwf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisaApplicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Gwf");

                    b.HasIndex("VisaApplicationId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("Share.Web.Models.IngestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccommodationsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Added")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlreadyPresent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Arrivals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CasesAdded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeopleAdded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsInFile")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatusesChanged")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("IngestRuns");
                });

            modelBuilder.Entity("Share.Web.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Share.Web.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Council")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchKey")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("Share.Web.Models.SkippedRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngestRunId");

                    b.ToTable("SkippedRow");
                });

            modelBuilder.Entity("Share.Web.Models.TimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IngestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisaApplicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("IngestRunId");

                    b.HasIndex("VisaApplicationId");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("Share.Web.Models.VisaApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Council")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gwf")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostFamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostGivenName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SponsorFamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SponsorGivenName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("StayingWithSponsor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmissionGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("CaseId");

                    b.HasIndex("Gwf");

                    b.HasIndex("HostId");

                    b.HasIndex("IngestRunId");

                    b.HasIndex("SponsorId");

                    b.HasIndex("SubmissionGuid")
                        .IsUnique();

                    b.HasIndex("Uan");

                    b.ToTable("VisaApplications");
                });

            modelBuilder.Entity("Share.Web.Models.ApplicationAnswer", b =>
                {
                    b.HasOne("Share.Web.Models.Guest", null)
                        .WithMany("Answers")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share.Web.Models.Case", b =>
                {
                    b.HasOne("Share.Web.Models.Accommodation", "Accommodation")
                        .WithMany()
                        .HasForeignKey("AccommodationId");

                    b.HasOne("Share.Web.Models.Person", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId");

                    b.Navigation("Accommodation");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Share.Web.Models.CaseCheck", b =>
                {
                    b.HasOne("Share.Web.Models.Case", null)
                        .WithMany("Checks")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share.Web.Models.DecisionUpdate", b =>
                {
                    b.HasOne("Share.Web.Models.IngestRun", "IngestRun")
                        .WithMany()
                        .HasForeignKey("IngestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Web.Models.VisaApplication", "VisaApplication")
                        .WithMany("DecisionUpdates")
                        .HasForeignKey("VisaApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestRun");

                    b.Navigation("VisaApplication");
                });

            modelBuilder.Entity("Share.Web.Models.Guest", b =>
                {
                    b.HasOne("Share.Web.Models.VisaApplication", "VisaApplication")
                        .WithMany("Guests")
                        .HasForeignKey("VisaApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisaApplication");
                });

            modelBuilder.Entity("Share.Web.Models.SkippedRow", b =>
                {
                    b.HasOne("Share.Web.Models.IngestRun", null)
                        .WithMany("SkippedRows")
                        .HasForeignKey("IngestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share.Web.Models.TimelineEvent", b =>
                {
                    b.HasOne("Share.Web.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId");

                    b.HasOne("Share.Web.Models.IngestRun", null)
                        .WithMany("Events")
                        .HasForeignKey("IngestRunId");

                    b.HasOne("Share.Web.Models.VisaApplication", "VisaApplication")
                        .WithMany()
                        .HasForeignKey("VisaApplicationId");

                    b.Navigation("Case");

                    b.Navigation("VisaApplication");
                });

            modelBuilder.Entity("Share.Web.Models.VisaApplication", b =>
                {
                    b.HasOne("Share.Web.Models.Accommodation", "Accommodation")
                        .WithMany("Applications")
                        .HasForeignKey("AccommodationId");

                    b.HasOne("Share.Web.Models.Case", "Case")
                        .WithMany("Applications")
                        .HasForeignKey("CaseId");

                    b.HasOne("Share.Web.Models.Person", "Host")
                        .WithMany("HostedApplications")
                        .HasForeignKey("HostId");

                    b.HasOne("Share.Web.Models.IngestRun", "IngestRun")
                        .WithMany()
                        .HasForeignKey("IngestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Share.Web.Models.Person", "Sponsor")
                        .WithMany("SponsoredApplications")
                        .HasForeignKey("SponsorId");

                    b.Navigation("Accommodation");

                    b.Navigation("Case");

                    b.Navigation("Host");

                    b.Navigation("IngestRun");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Share.Web.Models.Accommodation", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Share.Web.Models.Case", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Checks");
                });

            modelBuilder.Entity("Share.Web.Models.Guest", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Share.Web.Models.IngestRun", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SkippedRows");
                });

            modelBuilder.Entity("Share.Web.Models.Person", b =>
                {
                    b.Navigation("HostedApplications");

                    b.Navigation("SponsoredApplications");
                });

            modelBuilder.Entity("Share.Web.Models.VisaApplication", b =>
                {
                    b.Navigation("DecisionUpdates");

                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
