// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Share.Web.Data;

#nullable disable

namespace Share.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Share.Web.Models.ApplicationAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationPersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationPersonId");

                    b.ToTable("ApplicationAnswer");
                });

            modelBuilder.Entity("Share.Web.Models.ApplicationPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gwf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int>("VisaApplicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Gwf");

                    b.HasIndex("VisaApplicationId");

                    b.ToTable("ApplicationPeople");
                });

            modelBuilder.Entity("Share.Web.Models.IngestRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Added")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlreadyPresent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsInFile")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("IngestRuns");
                });

            modelBuilder.Entity("Share.Web.Models.SkippedRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngestRunId");

                    b.ToTable("SkippedRow");
                });

            modelBuilder.Entity("Share.Web.Models.TimelineEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IngestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("VisaApplicationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngestRunId");

                    b.HasIndex("VisaApplicationId");

                    b.ToTable("TimelineEvents");
                });

            modelBuilder.Entity("Share.Web.Models.VisaApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Council")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gwf")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngestRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SponsorFamilyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SponsorGivenName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmissionGuid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Gwf");

                    b.HasIndex("IngestRunId");

                    b.HasIndex("SubmissionGuid")
                        .IsUnique();

                    b.HasIndex("Uan");

                    b.ToTable("VisaApplications");
                });

            modelBuilder.Entity("Share.Web.Models.ApplicationAnswer", b =>
                {
                    b.HasOne("Share.Web.Models.ApplicationPerson", null)
                        .WithMany("Answers")
                        .HasForeignKey("ApplicationPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share.Web.Models.ApplicationPerson", b =>
                {
                    b.HasOne("Share.Web.Models.VisaApplication", "VisaApplication")
                        .WithMany("People")
                        .HasForeignKey("VisaApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisaApplication");
                });

            modelBuilder.Entity("Share.Web.Models.SkippedRow", b =>
                {
                    b.HasOne("Share.Web.Models.IngestRun", null)
                        .WithMany("SkippedRows")
                        .HasForeignKey("IngestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Share.Web.Models.TimelineEvent", b =>
                {
                    b.HasOne("Share.Web.Models.IngestRun", null)
                        .WithMany("Events")
                        .HasForeignKey("IngestRunId");

                    b.HasOne("Share.Web.Models.VisaApplication", "VisaApplication")
                        .WithMany()
                        .HasForeignKey("VisaApplicationId");

                    b.Navigation("VisaApplication");
                });

            modelBuilder.Entity("Share.Web.Models.VisaApplication", b =>
                {
                    b.HasOne("Share.Web.Models.IngestRun", "IngestRun")
                        .WithMany()
                        .HasForeignKey("IngestRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngestRun");
                });

            modelBuilder.Entity("Share.Web.Models.ApplicationPerson", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Share.Web.Models.IngestRun", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SkippedRows");
                });

            modelBuilder.Entity("Share.Web.Models.VisaApplication", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
